### ISSUE TITLE
Can't access http://compbio.cs.toronto.edu/silva/release/silva-1.1.1_data.tar.gz

### ISSUE THREAD

**Issue by tiagobrc** [buske/silva#3]
The server is down. Any prevision of when it will be active again?

**Comment by buske** [comment]
I believe this is related to a raid failure we're repairing. Investigating now. Thanks for the notice.

**Comment by buske** [comment]
@tiagobrc Sorry, we're still working on getting compbio.cs.toronto.edu back online. In the meantime, I was able to access the file you are interested in, so I uploaded it here: https://drive.google.com/open?id=0B7YZGwsGAChyNXhvQktRa2pXRkk

**Comment by tiagobrc** [comment]
Thank you very much!
